services:

  wordpress:
    image: wordpress:6.7-php8.2-apache
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    expose:
      - 80
    networks:
      wp-network:
        aliases:
          - ${APP_NETWORK}
    volumes:
      - ./wordpress/src:/var/www/html:rw
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "${IP}:${MYSQL_EXTERNAL_PORT}:3306"
    networks:
      wp-network:
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:1.26
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./data/nginx/certs:/etc/nginx/certs:ro
    ports:
      - "${IP}:80:80"
      - "${IP}:443:443"
    networks:
      wp-network:
        aliases:
          - ${DOMAIN1}
          - ${DOMAIN2}
    environment:
      - "NGINX_HOST=${DOMAIN1} ${DOMAIN2}"
      - NGINX_PORT=${NGINX_PORT}
      - APP_NETWORK=${APP_NETWORK}
      - APP_PORT=80
    tty: true

networks:
  wp-network:
